### ISSUE TITLE
Incompatible with Flash CS6

### ISSUE THREAD

**Issue by HaunGO** [stevensacks/Gaia-Framework#1]
When creating new GAIA project, the scaffolding process does not complete.

**Comment by ghost** [comment]
developing is stopped, i guess.

**Comment by hellonicolas** [comment]
@HaunGO We just tried to get started with CS6 and ran into the same issue.

Here's a workaround if you have access to Flash CS5.5 or older besides CS6:
- Make sure the Gaia panel is installed for both version of Flash Professional
- Create the Gaia project in CS5.5 or older (this part is _crucial_!!! creating the project in CS6 is what breaks everything else)
- Switch back to CS6 and do any subsequent edits! Scaffolding seems to work here too

I think the scaffolding fails because the CS6 messed up the project creation. The files each get their own folders of the same name. Might be related to some any changes in JSFL for Flash CS6?
![](http://d.pr/i/WXjZ+)

Hope that helps!

**Comment by ghost** [comment]
I did install when i had CS 5 and CS6 did not cause any problem. Like it came installed. @hellonicolas says the same thing.

**Comment by moskthescribe** [comment]
Not sure if this is still open - but I'm trying to get Gaia installed in Flash CS6 Pro to try the method you suggested - but can't get it installed.  Downloaded the Gaia framework from github, and that does include a Gaia Framework.mxi - but if I open that with Extension manager CS6 and try to import or install, just asks which extension sets to import - and seems to be looking for an xml file that it's not finding in the Gaia package.  Would love to get this working if possible - and I still have access to Flash CS4 so could try your method.
